### ISSUE TITLE
Configure Codeclimate RuboCop support

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday_middleware#260]
We are using latest version of RuboCop. We have specific plugins in play. CodeClimate can not import those.

Problem: Every time CodeClimate sees a new commit in the repo, it fails to make a report. And it shows a gray errored badge.

## Background

- [CodeClimate has a "channel" for which version of RuboCop is in use](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop).
- They also have a settings file `.codeclimate.yml`
- [CodeClimate RuboCop docs](https://docs.codeclimate.com/docs/rubocop)

## Example `.codeclimate.yml` file

We need 0-81: the latest available "channel" for RuboCop at CodeClimate.

Perhaps we also need a `.rubocop_codeclimate.yml` which inherits from `.rubocop.yml`, where we set the `require:` key to `[]`, so as to clear it.

```yaml
plugins:
  rubocop:
    enabled: true
    config:
      file: .rubocop_codeclimate.yml
    channel: rubocop-0-81
```
